###------------------------------------------------------------------------------------------------
# script:  details.inc
# purpose: Application specific details to assist in the generation of README.md
# version: 1.0.0
###------------------------------------------------------------------------------------------------

DETAILS_NAME="AWS Builder"
DETAILS_NAME_ABBR="aws_builder"
DETAILS_DESCRIPTION=(
    'Tools to assist in making AWS Infrastructure easier to manage, more robust, and more secure.'
)
DETAILS_PREREQUISITES=(
    'Linux'
    'BASH shell'
)
DETAILS_DEPENDENCIES=(
    'aws cli'
    'additional dependencies are required for specific Toolsets, please see the Required Executeables detail as indicated in the Library Function files'
)
